sudo: false

language: node_js

node_js:
    - node

before_script:
    - npm i -g npm@latest

script:
    - npm run build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GH_REPO_TOKEN
    keep-history: false
    local-dir: .docz/dist
    committer-from-gh: true
    on:
        branch:
            - master

notifications:
    email:
        on_success: never
